---
title: "ASSA COVID excess deaths calculations"
author: "Marc Burgess"
date: "04/03/2021"
output: html_document
---

## Exposure

Initial step is combining the exposure data from companies providing in standard format, to that of company 25 which provided more of a seriatim dataset. At the same time we clean up data types as we copy from `assa-lake` to `assa_sandbox` schema.

Output table is `covid_exposure`

```{sql exposure, eval=FALSE}
    WITH
        dib_to_use
        AS
            (  SELECT company_code, date_parse (effective_date, '%Y-%m-%d') AS effective_date, MAX (data_import_batch) AS max_batch
                 FROM "assa-lake".v1_covid_exposure
             GROUP BY company_code, date_parse (effective_date, '%Y-%m-%d')),
        dib_to_use_25
        AS
            (  SELECT year_month_of_file, MAX (data_import_batch) AS max_batch
                 FROM "assa-lake".v1_covid_inforce_25
             GROUP BY year_month_of_file),
        clean_data
        AS
            (SELECT company_code,
                    sex,
                    smoker_status,
                    age_band,
                    COALESCE (NULLIF (socio_economic_group, ''), 'UNKNOWN')     AS socio_economic_group,
                    date_parse (effective_date, '%Y-%m-%d')                     AS effective_date,
                    number_of_policies,
                    company_code                                                AS service_client_id,
                    data_import_batch
               FROM "assa-lake".v1_covid_exposure)
    SELECT clean_data.*
      FROM clean_data
           INNER JOIN dib_to_use
               ON     clean_data.company_code = dib_to_use.company_code
                  AND clean_data.effective_date = dib_to_use.effective_date
                  AND clean_data.data_import_batch = dib_to_use.max_batch
UNION ALL
  SELECT company_code
       ,gender       AS sex
        ,smoker_status
        ,CASE
             WHEN age < 20 THEN '<20'
             WHEN age >= 70 THEN '70+'
             ELSE CAST (10 * FLOOR (age / 10) AS VARCHAR) || ' - ' || CAST (10 * (FLOOR (age / 10) + 1) - 1 AS VARCHAR)
         END          age_band
        ,education    AS socio_economic_group
        ,effective_date
        ,COUNT (*)    AS number_of_policies
        ,company_code as service_client_id
        ,data_import_batch
    FROM (SELECT lake.*
                ,date_diff ('year', date_parse (date_of_birth, '%Y-%m-%d'),eff_date)     AS age
                ,eff_date                                                                AS effective_date
            FROM (values ('201812',date '2018-12-31'),('201912',date '2019-12-31'),('2020H1',date '2020-06-30'),('2020H2',date '2020-12-31'),('202101',date '2021-01-31'))  AS t(data_year_month,  eff_date)
                 LEFT JOIN ("assa-lake".v1_covid_inforce_25 lake INNER JOIN dib_to_use_25
                                                                      ON    lake.data_import_batch = dib_to_use_25.max_batch
                                                                        AND lake.year_month_of_file = dib_to_use_25.year_month_of_file)
                     ON lake.year_month_of_file = t.data_year_month AND date_parse(lake.policy_date_of_entry, '%Y-%m-%d') <= t.eff_date)
GROUP BY company_code
        ,gender
        ,smoker_status
        ,CASE
             WHEN age < 20 THEN '<20'
             WHEN age >= 70 THEN '70+'
             ELSE CAST (10 * FLOOR (age / 10) AS VARCHAR) || ' - ' || CAST (10 * (FLOOR (age / 10) + 1) - 1 AS VARCHAR)
         END
        ,education
        ,effective_date
        ,data_import_batch;

```

## Claims

We do the equivalent for claims data:

Output table is `covid_claims`

```{sql claims, eval=FALSE}
WITH
        dib_to_use
        AS
            (  SELECT company_code, MAX (data_import_batch) data_import_batch
                 FROM "assa-lake".v1_covid_claims
             GROUP BY company_code),
        dib_to_use_25_if
        AS
            (  SELECT year_month_of_file, MAX (data_import_batch) AS max_batch
                 FROM "assa-lake".v1_covid_inforce_25
             GROUP BY year_month_of_file),
        dib_to_use_25_clm
        AS
            (  SELECT MAX (data_import_batch) AS max_batch
                 FROM "assa-lake".v1_covid_claims_25)
    SELECT v1_covid_claims.company_code
          ,date_parse (date_data_received, '%Y-%m-%d')                                                                                             AS date_date_received
          ,sex
          ,REPLACE (smoker_status, 'smoker', 'Smoker')                                                                                             AS smoker_status
          ,CASE WHEN age_band = '60-70' THEN '60 - 69' ELSE REGEXP_REPLACE (age_band, '(?<rstart>\d+)-(?<rend>\d+)', '${rstart} - ${rend}') END    AS age_band
          ,                                                                                                        -- Make sure dashes have surrounding spaces
           socio_economic_class
          ,date_parse (year_and_month_of_date_of_death, '%Y-%m-%d')                                                                                AS year_and_month_of_date_of_death
          ,date_parse (NULLIF (year_and_month_of_date_reported, ''), '%Y-%m-%d')                                                                   AS year_and_month_of_date_reported
          ,number_of_natural_deaths_excl_covid
          ,number_of_covid_deaths
          ,number_of_unnatural_deaths
          ,total_number_of_natural_deaths_incl_covid
          ,total_claims
          ,v1_covid_claims.company_code                                                                                                            AS service_client_id
      FROM "assa-lake".v1_covid_claims
           INNER JOIN dib_to_use
               ON v1_covid_claims.company_code = dib_to_use.company_code AND v1_covid_claims.data_import_batch = dib_to_use.data_import_batch
    UNION ALL
      SELECT company_code
            ,date_parse (data_import_batch, '%Y-%m-%d')                                                                     date_data_received
            ,gender                                                                                                         AS sex
            ,smoker_status
            ,CASE
                 WHEN age < 20 THEN '<20'
                 WHEN age >= 70 THEN '70+'
                 ELSE CAST (10 * FLOOR (age / 10) AS VARCHAR) || ' - ' || CAST (10 * (FLOOR (age / 10) + 1) - 1 AS VARCHAR)
             END                                                                                                            age_band
            ,education                                                                                                      AS socio_economic_group
            ,date_parse (date_of_death, '%Y-%m-%d')                                                                         AS year_and_month_of_date_of_death
            ,date_parse (date_reported, '%Y-%m-%d')                                                                         AS year_and_month_of_date_reported
            ,  SUM (CASE WHEN natural_or_unnatural = 'Natural' AND covid19_ind = 'N' THEN 1 ELSE 0 END)
             + SUM (CASE WHEN natural_or_unnatural = 'Unknown' AND covid19_ind = 'N' THEN 1 ELSE 0 END * nat_prop)          AS number_of_natural_deaths_excl_covid
            ,SUM (CASE WHEN covid19_ind = 'Y' THEN 1 ELSE 0 END)                                                            number_of_covid_deaths
            ,  SUM (CASE WHEN natural_or_unnatural = 'Unnatural' AND covid19_ind = 'N' THEN 1 ELSE 0 END)
             + SUM (CASE WHEN natural_or_unnatural = 'Unknown' AND covid19_ind = 'N' THEN 1 ELSE 0 END * (1 - nat_prop))    AS number_of_unnatural_deaths
            ,  SUM (CASE WHEN natural_or_unnatural = 'Natural' OR covid19_ind = 'Y' THEN 1 ELSE 0 END)
             + SUM (CASE WHEN natural_or_unnatural = 'Unknown' AND covid19_ind = 'N' THEN 1 ELSE 0 END * nat_prop)          AS number_of_natural_deaths_incl_covid
            ,COUNT (*)                                                                                                      AS total_claims
            ,company_code                                                                                                   AS service_client_id
        FROM (SELECT /* Allocate Unknowns to Natural/Unnatural in proportion to business as a whole, at gender/age_band granularity */
                     dat0.*
                    ,  SUM (CASE WHEN natural_or_unnatural = 'Natural' THEN 1.0 ELSE 0.0 END)
                           OVER (PARTITION BY gender, LEAST (GREATEST (FLOOR (age / 10), 19), 70))
                     / SUM (CASE WHEN natural_or_unnatural != 'Unknown' THEN 1.0 ELSE 0.0 END)
                           OVER (PARTITION BY gender, LEAST (GREATEST (FLOOR (age / 10), 19), 70))    AS nat_prop
                FROM (SELECT clm.company_code
                            ,clm.data_import_batch
                            ,lake.policy_number
                            ,lake.life_number
                            ,lake.year_month_of_file                                                                                AS if_ym
                            ,lake.data_import_batch                                                                                 AS if_dib
                            ,lake.gender
                            ,date_of_death
                            ,date_reported
                            ,covid19_ind
                            ,natural_or_unnatural
                            ,education
                            ,REPLACE (smoker_status, 'smoker', 'Smoker')                                                            AS smoker_status
                            ,date_diff ('year', date_parse (date_of_birth, '%Y-%m-%d'), date_parse (date_of_death, '%Y-%m-%d'))     AS age
                            ,date_parse (date_of_death, '%Y-%m-%d')                                                                 AS effective_date
                        FROM ("assa-lake".v1_covid_claims_25                                  clm INNER JOIN dib_to_use_25_clm dib1 ON     clm.data_import_batch = dib1.max_batch)
                             LEFT JOIN
                             ("assa-lake".v1_covid_inforce_25 lake INNER JOIN dib_to_use_25_if dib2 ON     lake.data_import_batch = dib2.max_batch
                                                                                                       AND lake.year_month_of_file = dib2.year_month_of_file)
                                 ON lake.policy_number = clm.policy_number AND lake.life_number = clm.life_number
                       WHERE lake.policy_number IS NOT NULL) dat0) dat
             INNER JOIN (  SELECT policy_number, life_number, MAX (year_month_of_file) max_file, MAX(data_import_batch) max_dib
                             FROM "assa-lake".v1_covid_inforce_25
                         GROUP BY policy_number, life_number) fil
                 ON dat.policy_number = fil.policy_number AND dat.life_number = fil.life_number AND dat.if_ym = fil.max_file AND dat.if_dib = fil.max_dib
    GROUP BY company_code
            ,date_parse (data_import_batch, '%Y-%m-%d')
            ,gender
            ,smoker_status
            ,CASE
                 WHEN age < 20 THEN '<20'
                 WHEN age >= 70 THEN '70+'
                 ELSE CAST (10 * FLOOR (age / 10) AS VARCHAR) || ' - ' || CAST (10 * (FLOOR (age / 10) + 1) - 1 AS VARCHAR)
             END
            ,education
            ,date_parse (date_of_death, '%Y-%m-%d')
            ,date_parse (date_reported, '%Y-%m-%d')
```

## Combining claims and exposure

Now that we have cleaned up claims and exposure data it is possible to combine the two into a single table so that we can look at the crude mortality rates etc.

For exposure, we interpolate linearly between available exposure dates in order to estimate the number of policies in force in each month.

Output to `covid_actual_and_expected_deaths`

```{sql combined, eval=FALSE}
-- Note: Unless you save your query, these tabs will NOT persist if you clear your cookies or change browsers.

   WITH
        date_bounds
        AS
            (  SELECT                                            /* Split by company code and use analytic min/max to only use months available for all cos */
                      company_code
                     ,MIN (year_and_month_of_date_of_death)    AS min_death
                     ,MAX (year_and_month_of_date_of_death)    AS max_death
                     ,sequence (MIN (date_trunc ('month', year_and_month_of_date_of_death))
                               ,                                 --MAX (MIN (date_trunc ('month', year_and_month_of_date_of_death))) OVER (PARTITION BY NULL),
                                MAX (date_trunc ('month', year_and_month_of_date_of_death))
                               ,                                 --MIN (MAX (date_trunc ('month', year_and_month_of_date_of_death))) OVER (PARTITION BY NULL),
                                INTERVAL '1' MONTH)            AS month_seq
                 FROM assa_insights.covid_claims
             GROUP BY company_code),
        dates
        AS
            (SELECT DISTINCT clm_month
               FROM date_bounds CROSS JOIN unnest(month_seq) as t(clm_month)),
        avail_dates
        AS
            (  SELECT d1.company_code
                     ,clm_month
                     ,MAX (d1.effective_date)                                                                                AS prior_date
                     ,MIN (d2.effective_date)                                                                                AS next_date
                     ,date_diff ('month', date_trunc ('month', MAX (d1.effective_date)) + INTERVAL '1' MONTH, clm_month)     AS prior_lag
                     ,date_diff ('month', clm_month, date_trunc ('month', MIN (d2.effective_date)) + INTERVAL '1' MONTH)     AS next_lag
                 FROM dates
                      INNER JOIN assa_insights.covid_exposure d1 ON date_trunc ('month', d1.effective_date) + INTERVAL '1' MONTH <= clm_month
                      LEFT JOIN assa_insights.covid_exposure d2
                          ON date_trunc ('month', d2.effective_date) + INTERVAL '1' MONTH > clm_month AND d1.company_code = d2.company_code
             GROUP BY d1.company_code, clm_month),
        smoker_pcts
        AS
            (  SELECT claims.sex
                     ,claims.age_band
                     ,CASE
                          WHEN SUM (COALESCE (total_claims, 0)) = 0
                          THEN
                              0
                          ELSE
                                SUM (CASE WHEN smoker_status = 'Smoker' THEN CAST (COALESCE (total_claims, 0) AS DOUBLE) ELSE 0 END)
                              / SUM (COALESCE (total_claims, 0))
                      END    AS clm_smoker_pct
                 FROM assa_insights.covid_claims claims
                WHERE claims.smoker_status IN ('Smoker', 'Non-Smoker')
             GROUP BY claims.sex, claims.age_band),
        exposure
        AS
            (SELECT cur_year.company_code
                   ,cur_year.sex
                   ,cur_year.smoker_status
                   ,cur_year.age_band
                   ,cur_year.socio_economic_group
                   ,avail_dates.clm_month
                   ,  (1.0 / 12.0)
                    * CASE
                          WHEN next_year.effective_date IS NULL THEN cur_year.number_of_policies
                          ELSE (cur_year.number_of_policies * next_lag + next_year.number_of_policies * prior_lag) / (prior_lag + next_lag)
                      END    AS life_years
               FROM avail_dates
                    INNER JOIN assa_insights.covid_exposure cur_year
                        ON avail_dates.prior_date = cur_year.effective_date AND avail_dates.company_code = cur_year.company_code
                    LEFT JOIN assa_insights.covid_exposure next_year
                        ON     cur_year.company_code = next_year.company_code
                           AND cur_year.sex = next_year.sex
                           AND cur_year.smoker_status = next_year.smoker_status
                           AND cur_year.age_band = next_year.age_band
                           AND cur_year.socio_economic_group = next_year.socio_economic_group
                           AND avail_dates.next_date = next_year.effective_date)
    SELECT exposure.company_code
          ,exposure.sex
          ,exposure.smoker_status
          ,exposure.age_band
          ,exposure.socio_economic_group
          ,clm_month
          ,life_years
          ,0.0                       AS natural_deaths_excl_covid
          ,0.0                       AS covid_deaths
          ,0.0                       AS unnatural_deaths
          ,0.0                       AS total_deaths
          ,'exp'                     AS rec_type
          ,exposure.company_code     AS service_client_id
      FROM exposure
     WHERE smoker_status IN ('Smoker', 'Non-Smoker')
    UNION ALL
    SELECT claims.company_code
          ,claims.sex
          ,claims.smoker_status
          ,claims.age_band
          ,claims.socio_economic_class                                      AS socio_economic_group
          ,date_trunc ('month', claims.year_and_month_of_date_of_death)     AS clm_month
          ,0                                                                AS life_years
          ,COALESCE (number_of_natural_deaths_excl_covid, 0)                AS natural_deaths_excl_covid
          ,COALESCE (number_of_covid_deaths, 0)                             AS covid_deaths
          ,COALESCE (number_of_unnatural_deaths, 0)                         AS unnatural_deaths
          ,COALESCE (total_claims, 0)                                       AS total_deaths
         ,'clm'                                                            AS rec_type
          ,claims.company_code                                              AS service_client_id
      FROM assa_insights.covid_claims claims
     WHERE claims.smoker_status IN ('Smoker', 'Non-Smoker')
    /* Append reallocated unknown smoker_status claims to smoker and non-smoker */
    UNION ALL
    SELECT claims.company_code
          ,claims.sex
          ,'Smoker'                                                               AS smoker_status
          ,claims.age_band
          ,claims.socio_economic_class                                            AS socio_economic_group
          ,date_trunc ('month', claims.year_and_month_of_date_of_death)           AS clm_month
          ,0                                                                      AS life_years
          ,COALESCE (number_of_natural_deaths_excl_covid, 0) * clm_smoker_pct     AS natural_deaths_excl_covid
          ,COALESCE (number_of_covid_deaths, 0) * clm_smoker_pct                  AS covid_deaths
          ,COALESCE (number_of_unnatural_deaths, 0) * clm_smoker_pct              AS unnatural_deaths
          ,COALESCE (total_claims, 0) * clm_smoker_pct                            AS total_deaths
          ,'clm'                                                                  AS rec_type
          ,claims.company_code                                                    AS service_client_id
      FROM assa_insights.covid_claims claims INNER JOIN smoker_pcts ON claims.age_band = smoker_pcts.age_band AND claims.sex = smoker_pcts.sex
     WHERE claims.smoker_status NOT IN ('Smoker', 'Non-Smoker')
    UNION ALL
    SELECT claims.company_code
          ,claims.sex
          ,'Non-Smoker'                                                                 AS smoker_status
          ,claims.age_band
          ,claims.socio_economic_class                                                  AS socio_economic_group
          ,date_trunc ('month', claims.year_and_month_of_date_of_death)                 AS clm_month
          ,0                                                                            AS life_years
          ,COALESCE (number_of_natural_deaths_excl_covid, 0) * (1 - clm_smoker_pct)     AS natural_deaths_excl_covid
          ,COALESCE (number_of_covid_deaths, 0) * (1 - clm_smoker_pct)                  AS covid_deaths
          ,COALESCE (number_of_unnatural_deaths, 0) * (1 - clm_smoker_pct)              AS unnatural_deaths
          ,COALESCE (total_claims, 0) * (1 - clm_smoker_pct)                            AS total_deaths
          ,'clm'                                                                        AS rec_type
          ,claims.company_code                                                          AS service_client_id
      FROM assa_insights.covid_claims claims INNER JOIN smoker_pcts ON claims.age_band = smoker_pcts.age_band AND claims.sex = smoker_pcts.sex
     WHERE claims.smoker_status NOT IN ('Smoker', 'Non-Smoker')


```

## Standardisation

The final step is to calculate expected claims for 2020 given the observed crude rates and the actual exdposure data.

Output to `covid_standardised_ave`

```{sql standardised, eval = FALSE}
        WITH
        covid_months
        AS
            (SELECT DISTINCT clm_month
               FROM assa_insights.covid_actual_and_expected_deaths
              WHERE clm_month >= DATE '2020-01-01'), -- DATE '2020-03-01'),
       covid_groups
        AS
            (SELECT DISTINCT company_code
                            ,sex
               ,smoker_status
                            ,age_band
                            ,socio_economic_group
             FROM assa_insights.covid_actual_and_expected_deaths),
        monthly_expected_rates
        AS
            (  SELECT company_code
                     ,EXTRACT (MONTH FROM clm_month)      month_of_year
                     ,sex
 ,age_band
                     ,smoker_status
                     ,SUM (total_deaths)                  total_deaths
                     ,SUM (smoothed_total_deaths)         smoothed_total_deaths
                     ,SUM (unnatural_deaths)              unnatural_deaths
                     ,SUM (smoothed_unnatural_deaths)     smoothed_unnatural_deaths
                     ,SUM (life_years)                    life_years
                     ,SUM (smoothed_life_years)           smoothed_life_years
                 FROM (  SELECT company_code
                               ,clm_month
                               ,sex
                               ,age_band
                             ,smoker_status
                               ,SUM (total_deaths)                                                     total_deaths
                               ,SUM (SUM (total_deaths))
                                    OVER (PARTITION BY company_code, sex, age_band, smoker_status ORDER BY clm_month ROWS BETWEEN 2 PRECEDING AND 2 FOLLOWING)    smoothed_total_deaths
                               ,SUM (unnatural_deaths)                                           unnatural_deaths
                               ,SUM (SUM (unnatural_deaths))
                                    OVER (PARTITION BY company_code, sex, age_band, smoker_status ORDER BY clm_month ROWS BETWEEN 2 PRECEDING AND 2 FOLLOWING)    smoothed_unnatural_deaths
                               ,SUM (life_years)                                     life_years
                               ,SUM (SUM (life_years))
                                    OVER (PARTITION BY company_code, sex, age_band, smoker_status ORDER BY clm_month ROWS BETWEEN 2 PRECEDING AND 2 FOLLOWING)    smoothed_life_years
                           FROM assa_insights.covid_actual_and_expected_deaths
                       WHERE clm_month < DATE '2020-01-01' -- DATE '2020-03-01'
                       GROUP BY company_code
               ,clm_month
                               ,sex
                               ,age_band
                           ,smoker_status
                         HAVING SUM (life_years) > 0)
             GROUP BY company_code
           ,EXTRACT (MONTH FROM clm_month)
                     ,sex
                     ,age_band
                     ,smoker_status),
        covid_actuals
        AS
            (  SELECT covid_months.clm_month
                     ,EXTRACT (MONTH FROM covid_months.clm_month)                           month_of_year
                     ,exps.company_code
                     ,exps.sex
                     ,exps.smoker_status
                     ,exps.age_band
 ,exps.socio_economic_group
                     ,SUM (COALESCE (life_years, 0))                                       life_years
                     ,SUM (COALESCE (total_deaths, 0))                                      total_deaths
 ,SUM (COALESCE (natural_deaths_excl_covid, 0))                         natural_deaths_excl_covid
                     ,SUM (COALESCE (covid_deaths, 0))                                      covid_deaths
                     ,SUM (COALESCE (unnatural_deaths, 0))                                  unnatural_deaths
                     ,SUM (SUM (total_deaths)) OVER (PARTITION BY exps.company_code, covid_months.clm_month)  cont_total_claims
                 FROM (covid_months CROSS JOIN covid_groups)
                      LEFT JOIN assa_insights.covid_actual_and_expected_deaths exps
 ON     exps.clm_month = covid_months.clm_month
                             AND exps.company_code = covid_groups.company_code
                             AND exps.sex = covid_groups.sex
                             AND exps.smoker_status = covid_groups.smoker_status
                             AND exps.age_band = covid_groups.age_band
           AND exps.socio_economic_group = covid_groups.socio_economic_group
             GROUP BY covid_months.clm_month
     ,exps.company_code
                     ,exps.sex
                     ,exps.smoker_status
                     ,exps.age_band
                     ,exps.socio_economic_group)
                     --select sex, smoker_status, age_band, sum(total_Deaths), sum(life_years) from covid_actuals where company_code = 6 group by sex, smoker_status, age_Band
      SELECT act.company_code
            ,act.sex
            ,act.smoker_status
            ,act.age_band
   ,act.socio_economic_group
            ,act.clm_month
            ,act.clm_month                                     AS month_final
            ,SUM (act.life_years)                                                      AS life_years
 ,SUM (act.natural_deaths_excl_covid)                                       AS natural_deaths_excl_covid
            ,SUM (act.covid_deaths)                                                    AS covid_deaths
            ,SUM (act.unnatural_deaths)                                                AS unnatural_deaths
            ,SUM (act.total_deaths)   AS total_deaths
            ,SUM (exps.total_deaths) / SUM (exps.life_years)                           AS expected_death_rate
            ,SUM (exps.smoothed_total_deaths) / SUM (exps.smoothed_life_years)         AS smoothed_total_death_rate
            ,SUM (exps.unnatural_deaths) / SUM (exps.life_years)                       AS expected_unnatural_rate
            ,SUM (exps.smoothed_unnatural_deaths) / SUM (exps.smoothed_life_years)     AS smoothed_unnatural_death_rate
            ,CAST(act.company_code AS VARCHAR)                                         AS service_client_id
 FROM covid_actuals act
             LEFT JOIN monthly_expected_rates exps
                 ON act.company_code = exps.company_code AND act.sex = exps.sex AND act.age_band = exps.age_band AND act.month_of_year = exps.month_of_year AND act.smoker_status = exps.smoker_status
       WHERE act.sex IS NOT NULL AND act.cont_total_claims >= 50 -- Exclude months where very few claims have been reported yet
    GROUP BY act.company_code
            ,act.sex
            ,act.smoker_status
            ,act.age_band
            ,act.socio_economic_group
            ,act.clm_month
       --,exps.total_deaths
            --,exps.unnatural_deaths
            --,exps.smoothed_total_deaths
            --,exps.smoothed_unnatural_deaths
            --,exps.life_years
            --,exps.smoothed_life_years
   UNION ALL
      SELECT 901                                                                       AS company_code
            ,act.sex
            ,act.smoker_status
            ,act.age_band
            ,act.socio_economic_group
           ,act.clm_month
            ,act.clm_month                                                             AS month_final
            ,SUM (act.life_years)                                                      AS life_years
            ,SUM (act.natural_deaths_excl_covid)                                       AS natural_deaths_excl_covid
            ,SUM (act.covid_deaths)                                                    AS covid_deaths
            ,SUM (act.unnatural_deaths)                                                AS unnatural_deaths
            ,SUM (act.total_deaths)       AS total_deaths
            ,SUM (exps.total_deaths) / SUM (exps.life_years)                           AS expected_death_rate
            ,SUM (exps.smoothed_total_deaths) / SUM (exps.smoothed_life_years)         AS smoothed_total_death_rate
            ,SUM (exps.unnatural_deaths) / SUM (exps.life_years)                       AS expected_unnatural_rate
            ,SUM (exps.smoothed_unnatural_deaths) / SUM (exps.smoothed_life_years)     AS smoothed_unnatural_death_rate
            ,'901'                                                                     AS service_client_id
 FROM covid_actuals act
             INNER JOIN (SELECT company_code, MIN(MAX(clm_month)) OVER () last_month FROM covid_actuals WHERE total_deaths > 0 GROUP BY company_code) max_month
                 ON act.company_code = max_month.company_code AND act.clm_month <= max_month.last_month
             LEFT JOIN monthly_expected_rates exps
             ON act.company_code = exps.company_code AND act.sex = exps.sex AND act.age_band = exps.age_band AND act.month_of_year = exps.month_of_year AND act.smoker_status = exps.smoker_status
       WHERE act.sex IS NOT NULL
    GROUP BY act.sex
            ,act.smoker_status
            ,act.age_band
            ,act.socio_economic_group
            ,act.clm_month
            --,exps.total_deaths
            --,exps.unnatural_deaths
            --,exps.smoothed_total_deaths
            --,exps.smoothed_unnatural_deaths
            --,exps.life_years
            --,exps.smoothed_life_years
    -- HAVING SUM(act.life_years) > 0


```

## SAMRC

Used for chart comparing SAMRC to our data. Bit of work goes into interpolation so we can line the two dataset up nicely

Goes into `samrc_excess`

```{sql samrc, eval = FALSE}
WITH initdata AS (
    SELECT company_code
          ,'Population Deaths Relative to Expected'                 AS series
          ,date_parse (dth_date, '%Y-%m-%d') + INTERVAL '3' DAY     AS clm_month
          ,excess_deaths
          ,pred_deaths
          ,month_lims.service_client_id
      FROM "assa-lake".v1_samrc_excess
           CROSS JOIN (SELECT DISTINCT company_code, service_client_id
                         FROM assa_insights.covid_standardised_ave) month_lims
     WHERE data_import_batch = (SELECT MAX (data_import_batch) FROM "assa-lake".v1_samrc_excess)
    UNION ALL
    SELECT company_code
          ,'Baseline'                 AS series
          ,date_parse (dth_date, '%Y-%m-%d') + INTERVAL '3' DAY     AS clm_month
          ,0                                                        AS excess_deaths
          ,1                                                        AS pred_deaths
          ,month_lims.service_client_id
      FROM "assa-lake".v1_samrc_excess
           CROSS JOIN (SELECT DISTINCT company_code, service_client_id
                         FROM assa_insights.covid_standardised_ave) month_lims
     WHERE data_import_batch = (SELECT MAX (data_import_batch) FROM "assa-lake".v1_samrc_excess)
    UNION ALL
    SELECT company_code
                     ,'Insured Deaths Relative to Expected'                             AS series
                     ,month_final + INTERVAL '15' DAY                                   AS clm_month
                     ,SUM (total_deaths - (life_years * smoothed_total_death_rate))     AS excess_deaths
                     ,SUM (life_years * smoothed_total_death_rate)                      AS pred_deaths
                     ,service_client_id
                 FROM assa_insights.covid_standardised_ave
             GROUP BY company_code, month_final, service_client_id),
daterange AS (
    SELECT sequence(MIN(clm_month), MAX(clm_month), INTERVAL '1' DAY) AS dr FROM initdata
),
dateinterp AS (
    SELECT  pd.company_code
           ,pd.series
           ,ind_date
           ,pd.service_client_id
           ,MAX(pd.clm_month) AS prior_date
           ,MIN(nd.clm_month) AS next_date
           ,MAX_BY(pd.excess_deaths, pd.clm_month) AS prior_excess
           ,MAX_BY(pd.pred_deaths, pd.clm_month) AS prior_pred
           ,MIN_BY(nd.excess_deaths, nd.clm_month) AS next_excess
           ,MIN_BY(nd.pred_deaths, nd.clm_month) AS next_pred
           FROM daterange
           CROSS JOIN UNNEST(daterange.dr) AS ind_dates(ind_date)
           LEFT JOIN (initdata AS pd INNER JOIN initdata AS nd
           ON pd.company_code = nd.company_code AND pd.series = nd.series)
           ON ind_dates.ind_date >= pd.clm_month AND ind_dates.ind_date <= nd.clm_month
           GROUP BY pd.company_code, pd.series, ind_date, pd.service_client_id)
    SELECT company_code
          ,series
          ,ind_date                                                                                                                                AS clm_month
          ,prior_excess
          ,next_excess
          ,prior_pred
          ,next_pred
          ,prior_date
          ,next_date
          ,CASE
               WHEN prior_date != next_date THEN to_milliseconds (ind_date - prior_date) / CAST (to_milliseconds (next_date - prior_date) AS DOUBLE)
               ELSE 0
           END         AS interp_fac
          ,service_client_id
      FROM dateinterp

```